# CRIAR UM CRUD AQUI. 
# ESTE CRUD DEVE SER SIMPLES, ENTAO NAO HA NECESSIDADE DE USAR UM BANCO DE DADOS.
# VOU CONSTRUIR USANDO UM ARQUIVO CSV.
# COMO MODELO DE TRABALHO, VOU USAR O CONCEITO DE ESTACOES DE TRABALHO, WORKSTATIONS(WS).
# CABECALHO: (WS_ID, WS_NAME,         CITY, WORKERS) 
# EXEMPLO  : (    1, MOINHOS, PORTO ALEGRE,      33)
# POR CONVENCAO, OS NOMES DE VARIAVEIS SERAO EM INGLES.   

# READ A FILE IN CSV FORMAT

# BUILD AN INTERFACE TO WALK THROUGH THE CRUD

# C : CREATE A NEW LINE REGISTER

# R : READ ALL REGISTERS

# U : UPDATE A EXISTING REGISTER

# D : DELETE A EXISTING REGISTER

# EXTRA : READ 1 SPECIFIC REGISTER
