# build a crud here

# READ A FILE IN CSV FORMAT

# BUILD AN INTERFACE TO WALK THROUGH THE CRUD

# C : CREATE A NEW LINE REGISTER

# R : READ ALL REGISTERS

# U : UPDATE A EXISTING REGISTER

# D : DELETE A EXISTING REGISTER

# EXTRA : READ 1 SPECIFIC REGISTER
